ignore:
  - vulnerability: GHSA-3ppc-4f35-3m26
    include-aliases: true
    reason: >-
      Base image npm package: minimatch - bundled in Node.js base image, not fixable via application dependencies as of
      2026-02-23 (high severity)
  - vulnerability: CVE-2025-60876
    include-aliases: true
    reason: "Alpine base image package (apk): busybox - no npm fix available as of 2026-02-23 (moderate severity)"
  - vulnerability: GHSA-7h2j-956f-4vf2
    include-aliases: true
    reason: >-
      Base image npm package: @isaacs/brace-expansion - bundled in Node.js base image, not fixable via application
      dependencies as of 2026-02-23 (high severity)
  - vulnerability: GHSA-83g3-92jg-28cx
    include-aliases: true
    reason: >-
      Base image npm package: tar - bundled in Node.js base image, not fixable via application dependencies as of
      2026-02-23 (high severity)
  - vulnerability: GHSA-34x7-hfp2-rc4v
    include-aliases: true
    reason: >-
      Base image npm package: tar - bundled in Node.js base image, not fixable via application dependencies as of
      2026-02-23 (high severity)
  - vulnerability: CVE-2026-27171
    include-aliases: true
    reason: "Alpine base image package (apk): zlib - no npm fix available as of 2026-02-23 (moderate severity)"
  - vulnerability: GHSA-m7jm-9gc2-mpf2
    include-aliases: true
    reason: "Unfixable npm transitive vulnerability: fast-xml-parser (critical severity) as of 2026-02-23"
  - vulnerability: GHSA-jmr7-xgp7-cmfj
    include-aliases: true
    reason: "Unfixable npm transitive vulnerability: fast-xml-parser (high severity) as of 2026-02-23"
  - vulnerability: GHSA-p9pc-299p-vxgp
    include-aliases: true
    reason: "Unfixable npm transitive vulnerability: yargs-parser (moderate severity) as of 2026-02-23"
  - vulnerability: GHSA-2g4f-4pwh-qvx6
    include-aliases: true
    reason: "Unfixable npm transitive vulnerability: ajv (moderate severity) as of 2026-02-23"
output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
