ignore:
  # Ignore cross-spawn vulnerabilities by CVE ID
  - vulnerability: "CVE-2024-21538"
    package:
      name: "cross-spawn"

  # Ignore cross-spawn vulnerabilities by GHSA ID
  - vulnerability: "GHSA-3xgq-45jj-v275"
    package:
      name: "cross-spawn"

  # Ignore all vulnerabilities in cross-spawn
  - vulnerability: "*"
    package:
      name: "cross-spawn"

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count EXCLUDING cross-spawn
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
